version: "2"

services:
  cornerwise:
    build: .
    image: cornerwise
    env_file:
      - ./docker-support/common.env
    links:
      - postgres
      - redis
    command: bash /app/start.sh
    volumes:
      - runinfo:/runinfo
      - media:/media
  celery:
    image: cornerwise
    depends_on:
      - cornerwise
    env_file:
      - ./docker-support/common.env
    environment:
      IS_CELERY: "1"
    links:
      - postgres
      - redis
    volumes:
      - media:/media
    command: bash /app/celery_start.sh
  postgres:
    image: mdillon/postgis:9.4
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
  data:
    driver: local
  runinfo:
    driver: local
  media:
    driver: local
