version: "2"

services:
  cornerwise:
    image: bdsand/cornerwise:latest
    env_file:
      - ./docker-support/common.env
    environment:
      APP_PORT: "4000"
      APP_MODE: "development"
      GOOGLE_APPLICATION_CREDENTIALS: "/app/cornerwise/google_credentials.json"
      DJANGO_SERVE_STATIC: "1"
      DJANGO_SERVE_MEDIA: "1"
    ports:
      - "4000:4000"
    links:
      - postgres
      - redis
    working_dir: /app/
    command: bash /app/start.sh
    volumes:
      - media:/media
      - ./server:/app
      - ./client:/static
      - ./data:/data
      - ./docker-support:/support
    stdin_open: true
    tty: true
  postgres:
    image: mdillon/postgis:9.4
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
  data:
    driver: local
  media:
    driver: local
